name: deploy

on:   
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Check if ansible is installed
        run: ansible --version
